### ISSUE TITLE
TimerError when using tokio-retry 0.2 with old tokio-core crate

### ISSUE THREAD

**Issue by df5602** [srijs/rust-tokio-retry#8] opened 2018-04-09 21:23 UTC
Hi,

When running the second example (for the old tokio_core crate) in the documentation ([https://docs.rs/tokio-retry/0.2.0/tokio_retry/#using-the-tokio_core-crate](url)) I get a TimerError and no retries:

```
result Err(TimerError(Error(Shutdown)))
```

I don't really understand enough about tokio-timer to understand the error. Is there a step missing from the example?

**Comment by srijs** [comment] 2018-04-10 06:27
Hi @df5602, what‘s the exact version of tokio-core that you‘re seeing this problem with?

**Comment by srijs** [comment] 2018-04-10 08:15
I can reproduce locally now. It looks like this might be related to https://github.com/tokio-rs/tokio/issues/305, will investigate further later today!

**Comment by srijs** [comment] 2018-04-10 13:02
I raised https://github.com/tokio-rs/tokio-core/pull/320 that should fix this problem!

**Comment by df5602** [comment] 2018-04-10 17:16
Great, thanks a lot!

**Comment by srijs** [comment] 2018-04-11 17:06
`tokio-core` 0.1.17 was just released which includes the fix, so I'm going to close this now. Please let me know how it works for you!

I've also added a test for the compatibility with `tokio-core`, to make sure we don't regress here.

**Closed by srijs** 2018-04-11 17:06 UTC

**Comment by df5602** [comment] 2018-04-11 20:55
Hi, works like a charm now, thanks a lot!
